# Generated by Django 4.1.2 on 2022-12-08 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sitio'),
        ),
        migrations.AddField(
            model_name='sitio',
            name='visitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
