# Generated by Django 4.1.2 on 2022-12-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sitio_image_sitio_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
