# Generated by Django 4.1.2 on 2022-12-08 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_sitio_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurante'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
