# Generated by Django 4.1.2 on 2022-12-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_restaurante_image_restaurante_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitio',
            old_name='visitante',
            new_name='owner',
        ),
    ]
