# Generated by Django 4.1.2 on 2022-12-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_visitante_sitio_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monumento',
            name='fecha',
        ),
    ]
