# Generated by Django 4.1.2 on 2022-12-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_monumento_created_at_monumento_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
