# Generated by Django 4.1.2 on 2022-12-08 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_restaurante_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
