# Generated by Django 4.1.2 on 2022-12-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_restaurante_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='description',
        ),
    ]
