# Generated by Django 4.1.2 on 2022-12-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_restaurante_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumento',
            name='experiencia',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sitio',
            name='experiencia',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
