# Generated by Django 4.1.2 on 2022-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_monumento_experiencia_sitio_experiencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monumento',
            old_name='experiencia',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='experiencia',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='monumento',
            name='historia',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sitio',
            name='historia',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
